name: Events Demo 1
on:
  pull_request:
    types:
      - opened
      - edited
  workflow_dispatch:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      script-files: ${{ steps.publ.outputs.something }}
    steps:
      - name: Output event data
        run: echo "${{ toJSON(github.event) }}"
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Test code
        run: npm run test
      - name: Build code
        run: npm run build
      - name: publish JS file
        id: publ
        run: find dist/assets/*.js -type f -execdir echo 'something={}' >> $GITHUB_OUTPUT ';'
      - name: upload artifacts
        uses: actions/upload-artifact@v7
        with:
          name: dist-files
          path: dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get build atifacts
        uses: actions/download-artifact@v4
        with:
          name: dist-files
      - name: output contents
        run: ls
      - name: output filename
        run: echo "${{ needs.build.outputs.script-files }}"
      - name: Deploy
        run: echo "Deploying....."
  
  report:
    needs: build
    uses: ./.github/workflows/reports.yml
    with: 
      artifact_name: dist-files
  
  print:
    needs: report
    runs-on: ubuntu-latest
    steps: 
      - name: print final output
        run: |
          echo "Final output is: ${{ needs.report.outputs.script_out }}"